# -*- coding: utf-8 -*-
import os
import re
import shutil
import subprocess
import sys
import warnings
import xml.etree.ElementTree as ET
from datetime import date

from sphinx_scylladb_theme.utils import multiversion_regex_builder

sys.path.insert(0, os.path.abspath(".."))

# -- Global variables

# Builds documentation for the following tags and branches.
TAGS = ["v1.0.0", "v1.0.1", "v1.1.0", "v1.1.1", "v1.1.2"]
BRANCHES = [
    "master",
]
# Sets the latest version.
LATEST_VERSION = "v1.1.2"
# Set which versions are not released yet.
UNSTABLE_VERSIONS = ["master"]
# Set which versions are deprecated
DEPRECATED_VERSIONS = ["v1.0.0", "v1.0.1", "v1.1.0", "v1.1.1"]
# Sets custom build.
FLAGS = ["theme"]

# -- General configuration ------------------------------------------

# Add any Sphinx extension module names here, as strings.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.todo",
    "sphinx.ext.mathjax",
    "sphinx.ext.githubpages",
    "sphinx.ext.extlinks",
    "sphinx_sitemap",
    "sphinx_scylladb_theme",
    "sphinx_multiversion",  # optional
    "myst_parser",  # optional
    "breathe",
    "sphinx_scylladb_markdown",
]

# The suffix(es) of source filenames.
source_suffix = [".rst", ".md"]

# The master toctree document.
master_doc = "contents"

# General information about the project.
project = "ScyllaDB CPP RS Driver"
copyright = str(date.today().year) + ", ScyllaDB. All rights reserved."
author = "ScyllaDB Project Contributors"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", ".venv"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# List of substitutions
rst_prolog = """
.. |rst| replace:: restructuredText
"""

# -- Options for myst parser ----------------------------------------
myst_enable_extensions = ["colon_fence"]

# -- Options for not found extension --------------------------------

# Template used to render the 404.html generated by this extension.
notfound_template = "404.html"

# Prefix added to all the URLs generated in the 404 page.
notfound_urls_prefix = ""

# -- Options for sitemap extension ----------------------------------

sitemap_url_scheme = "/stable/{link}"

# -- Options for llms.txt extension ---------------------------------

# Run the llms.txt markdown pass after the main build finishes. Under
# sphinx-multiversion the markdown subprocess re-reads the temporary git
# checkout with the checked-out conf.py, which rewrites the generated
# api/*.rst sources; building sequentially avoids racing the main build.
llms_txt_build_parallel = False

# -- Options for multiversion extension -----------------------------

# Whitelist pattern for tags
smv_tag_whitelist = multiversion_regex_builder(TAGS)
# Whitelist pattern for branches
smv_branch_whitelist = multiversion_regex_builder(BRANCHES)
# Defines which version is considered to be the latest stable version.
smv_latest_version = LATEST_VERSION
# Defines the new name for the latest version.
smv_rename_latest_version = "stable"
# Whitelist pattern for remotes (set to None to use local branches only)
smv_remote_whitelist = r"^origin$"
# Pattern for released versions
smv_released_pattern = r"^tags/.*$"
# Format for versioned output directories inside the build directory
smv_outputdir_format = "{ref.name}"
# -- Options for HTML output ----------------------------------------

html_static_path = ["_static"]

# -- Options for Doxygen (API Reference)
breathe_projects = {"API": "../../doxygen/xml/"}
breathe_default_project = "API"
breathe_default_members = ("members", "undoc-members")

# Hide parent class names in sidebar
toc_object_entries_show_parents = "hide"


# Autogenerate API reference
def _generate_structs(outdir, structs, project):
    """Write structs docs in the designated outdir folder"""
    for obj in structs:
        with open(outdir / f"struct.{obj}.rst", "w") as t_file:
            t_file.write(
                obj
                + "\n"
                + "=" * len(obj)
                + "\n\n"
                + ".. doxygenstruct:: "
                + obj
                + " \n  :project: "
                + project
            )


def _generate_groups(outdir, groups, project):
    """Write structs docs in the designated outdir folder"""
    for obj in groups:
        with open(outdir / f"group.{obj}.rst", "w") as t_file:
            t_file.write(
                obj
                + "\n"
                + "=" * len(obj)
                + "\n\n"
                + ".. doxygengroup:: "
                + obj
                + "\n  :project: "
                + breathe_default_project
                + "\n  :content-only:"
            )


def _generate_doxygen_rst(xml_path, outdir):
    """Autogenerate doxygen docs in the designated outdir folder"""
    structs = []
    groups = []
    group_structs = set()
    files = os.listdir(xml_path)
    for file_name in files:
        if file_name.startswith("group__") and file_name.endswith(".xml"):
            tree = ET.parse(os.path.join(xml_path, file_name))
            root = tree.getroot()
            compoundname = root.find(".//compoundname")
            if compoundname is not None and compoundname.text:
                group_name = compoundname.text
                groups.append(group_name)
            for inner in root.iter("innerclass"):
                group_structs.add(inner.text)
    for file_name in files:
        if "struct" in file_name and "__" not in file_name:
            name = (
                file_name.replace("struct_", "")
                .replace("_", " ")
                .replace(".xml", "")
                .title()
                .replace(" ", "")
            )
            if name not in group_structs:
                structs.append(name)
    _generate_structs(outdir, structs, breathe_default_project)
    _generate_groups(outdir, groups, breathe_default_project)


def _resolve_doxygen_xml(xmldir, srcdir):
    real_xml = os.path.abspath(os.path.join(os.path.dirname(__file__), xmldir))
    checkout_xml = os.path.abspath(os.path.join(srcdir, xmldir))
    if checkout_xml != real_xml:
        doxygen = shutil.which("doxygen")
        if doxygen is None:
            raise RuntimeError("doxygen not found in PATH (run 'make setup')")
        checkout_root = os.path.abspath(os.path.join(srcdir, "..", ".."))
        subprocess.run([doxygen, "Doxyfile.in"], cwd=checkout_root, check=True)
        return checkout_xml
    return real_xml


def generate_doxygen(app):
    xml_path = _resolve_doxygen_xml(
        breathe_projects[breathe_default_project], app.builder.srcdir
    )
    app.config.breathe_projects = {breathe_default_project: xml_path}
    _generate_doxygen_rst(xml_path, app.builder.srcdir / "api")


# -- Options for sitemap extension

sitemap_url_scheme = "/stable/{link}"

# The theme to use for pages.
html_theme = "sphinx_scylladb_theme"
html_theme_path = ["../.."]

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for the theme, see the
# documentation.
html_theme_options = {
    "conf_py_path": "docs/source/",
    "hide_edit_this_page_button": "false",
    "hide_feedback_buttons": "false",
    "github_issues_repository": "scylladb/cpp-rs-driver",
    "github_repository": "scylladb/cpp-rs-driver",
    "site_description": "API-compatible rewrite of scylladb/cpp-driver as a wrapper over ScyllaDB Rust driver.",
    "hide_version_dropdown": [],
    "zendesk_tag": "gq6ltsh3nfex3cnwfy4aj9",
    "versions_unstable": UNSTABLE_VERSIONS,
    "versions_deprecated": DEPRECATED_VERSIONS,
}

# Last updated format
html_last_updated_fmt = "%d %b %Y"

# Custom sidebar templates, maps document names to template names.
html_sidebars = {"**": ["side-nav.html"]}

# Output file base name for HTML help builder.
htmlhelp_basename = "ScyllaDocumentationdoc"

# URL which points to the root of the HTML documentation.
html_baseurl = "https://cpp-rs-driver.docs.scylladb.com"

# Dictionary of values to pass into the template engine’s context for all pages
html_context = {"html_baseurl": html_baseurl}

# -- Initialize Sphinx ----------------------------------------------


def setup(sphinx):
    warnings.filterwarnings(
        action="ignore",
        category=UserWarning,
        message=r".*Container node skipped.*",
    )

    sphinx.add_css_file("custom.css")

    # Autogenerate API Reference
    sphinx.connect("builder-inited", generate_doxygen)
